#!/usr/bin/env python
import sys, os, json
import argparse
import snakemake

logo = """
 _______  _______  _______  _______
|       ||   _   ||       ||       |
|_     _||  |_|  ||       ||   _   |
  |   |  |       ||       ||  | |  |
  |   |  |       ||      _||  |_|  |
  |   |  |   _   ||     |_ |       |
  |___|  |__| |__||_______||_______|

experimental CL interface for dahak workflows
"""


pwd = os.path.abspath(os.path.dirname(__file__))


def main(args):

    # Snakefile needs to be in current directory
    snakefile = os.path.join(pwd, 'Snakefile')
    if(not os.path.exists(snakefile)):
        sys.stderr.write('Error: cannot find Snakefile at {}\n'.format(snakefile))
        sys.exit(-1)


    # Workflow file should be next arg
    workflowfile = None
    if(args.workflowfile=='ls'):
        # This is a hack
        status = snakemake.snakemake(snakefile, 
                listrules=True)
        return 0

    elif os.path.exists(args.workflowfile) and not os.path.isdir(args.workflowfile):
        workflowfile = args.workflowfile
    else:
        for suffix in ('', '.json'):
            tryfile = os.path.join(pwd, args.workflowfile + suffix)
            if os.path.exists(tryfile) and not os.path.isdir(tryfile):
                sys.stderr.write('Found workflowfile at {}\n'.format(tryfile))
                workflowfile = tryfile
                break

    if not workflowfile:
        sys.stderr.write('Error: cannot find workflowfile {}\n'.format(args.workflowfile))
        sys.exit(-1)

    # Next, find the workflow params file
    paramsfile = None
    if os.path.exists(args.paramsfile) and not os.path.isdir(args.paramsfile):
        paramsfile = args.paramsfile
    else:
        for suffix in ('', '.json'):
            tryfile = os.path.join(pwd, args.paramsfile + suffix)
            if os.path.exists(tryfile) and not os.path.isdir(tryfile):
                sys.stderr.write('Found paramsfile at {}\n'.format(tryfile))
                paramsfile = tryfile
                break

    if not paramsfile:
        sys.stderr.write('Error: cannot find paramsfile {}\n'.format(args.paramsfile))
        sys.exit(-1)

    with open(workflowfile, 'rt') as fp:
        workflow_info = json.load(fp)

    target = workflow_info['workflow_target']

    config = dict()

    print('--------')
    print('taco workflow details:')
    print('\tsnakefile: {}'.format(snakefile))
    print('\tconfig: {}'.format(workflowfile))
    print('\tparams: {}'.format(paramsfile))
    print('\ttarget: {}'.format(target))
    print('--------')

    status = snakemake.snakemake(snakefile, 
                                 configfile=paramsfile,
                                 targets=[target], 
                                 printshellcmds=True,
                                 dryrun=args.dry_run, 
                                 config=config)

    if status: # translate "success" into shell exit code of 0
        return 0
    return 1



if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='taco: the experimental dahak cli', usage='''taco <workflow> <parameters> [<target>]

taco is an experimental command line interface for running dahak workflows.

For the full documentation, visit:

    https://charlesreid1.github.io/dahak-taco/

For a quick start, visit:

    https://charlesreid1.github.io/dahak-taco/intro/quickstart.html

Users should provide a <workflow> JSON file and a <parameters> JSON file.
These should specify a relative path to JSON files (with or without
the JSON extension).

To get more help, run ./taco --help

\r\r''')

    # We provide the user with a "taco ls" command
    # by making "paramsfile" optional,
    # and checking if "workflowfile" is "ls".
    #
    # This hack is acceptable for this one subcommand,
    # but if we want to add more subcommands, we should
    # create multiple parsers like civilized people.
    #
    parser.add_argument('workflowfile', help="""To specify a workflow, create a JSON file containing the name of the Snakemake rules you wish to run.""")
    parser.add_argument('paramsfile', help="""Specify parameters using a JSON file, and pass the name of the JSON file.""", nargs='*')
    parser.add_argument('-n', '--dry-run', action='store_true')
    args = parser.parse_args()

sys.exit(main(args))

