FROM ubuntu:16.04
MAINTAINER cmreid@ucdavis.edu 

RUN apt-get update && apt-get -y install git curl bzip2 perl

WORKDIR /work

ENV VERSION miniconda3-4.3.30
ENV PYENV /work/.pyenv/bin/pyenv
ENV CONDA /work/.pyenv/shims/conda

RUN curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

RUN ${PYENV} update
RUN ${PYENV} install $VERSION
RUN ${PYENV} global $VERSION

#RUN ${CONDA} update
RUN ${CONDA} config --add channels defaults
RUN ${CONDA} config --add channels conda-forge
RUN ${CONDA} config --add channels bioconda

RUN ${CONDA} install -c conda-forge openjdk fastqc

ENV PATH "/work/.pyenv/shims:/work/.pyenv/bin:${PATH}"


