FROM tzenderman/docker-pyenv:latest

WORKDIR /work

COPY .python-version /work/.python-version
COPY requirements.txt /work/requirements.txt

RUN yes | pyenv install $(cat .python-version) && \
    pip install -r /code/requirements.txt

